# Generated by Django 4.0.3 on 2022-08-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_blah'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blah',
        ),
    ]
